### ISSUE TITLE
JavaScriptRenderer generates invalid markup

### ISSUE THREAD

**Issue by sgittel** [mtils/php-ems#38]
Hi @mtils,
Ems\Assets\Renderer\JavascriptRenderer::renderExternal() contains an invalid quote sign near the end of the script tag thus rendering invalid HTML markup.
```php
//                                                                            error is here ↴
return '<script '.$this->renderAttributes(['src' => $asset->uri()], $asset->attributes()).' "></script>';
```
should instead be
```php
return '<script '.$this->renderAttributes(['src' => $asset->uri()], $asset->attributes()).'></script>';
```

**Comment by mtils** [comment]
Oh yes you are right ;-) To be honest I planned to remove the most Assets Stuff. Which version of php-ems do you use currently? I will eventually backport it.
